class Netflix{
static String kannadamovies[]={"kanthara","uturn","Ayana","mundina nildana","avatara purusha1","avatharapurusha2","777 charlie","kgf","kgf2","milana","akash","ranavikrama","2nakshathra","99","lakky","kiratara damanaka","kirathaka","adyaksha1","nalla","kanasugara","bajarangi","kavacha","vishnuvardana","kotigobba","jogi"};
static String hindiMovies[]={"toby","raana","banaras","khakii","dhwaja","house of spies","bulbbul","murder mubarak","jaane jaan","bhakshak","pagglait","gunjan saxena","chor nikal ke","mrs serial killer","haseen dilluruba","qala","ginny weds sunny","kathal","monica","sardar ka grandson","jaadugar","jogi","darling","maska","dasvi"};
static String englishMovies[]={"damsel","spaceman","atlas","hit man","rebel moon","enola holmes","munich","society of the snow","the killer","glass onion","magician","the ritual","the gray man","exraction","hear of stone","luther","geralds game","red noticec","leo","extraction2","ultraman","big george foreman","gran turismo","king richard","no hard feelings"};
static String koreanSeries[]={"its okay to not be okay","marriage contract","business proposal","the secret life of my secretary","strong girl bong soon","clean with passion for now","the a typical family","suspicious partner","destined with you","gangnam beauty","tomorrow","the ritual","the gray man","good manager","crash landing on you","she would never know","my demon","romantic","warm and cozy","vencenzo" };
public static void main(String [] netflix){
System.out.println(" the kannada movies available in netfilx are:"+ "\n" +kannadamovies[0]+"\n"+kannadamovies[1]+"\n"+kannadamovies[2]+"\n"+kannadamovies[3]+"\n"+kannadamovies[4]+"\n"+kannadamovies[5]+"\n"+kannadamovies[6]+"\n"+kannadamovies[7]+"\n"+kannadamovies[8]+"\n"+kannadamovies[9]+ "\n" +kannadamovies[10]+"\n"+kannadamovies[11]+"\n"+kannadamovies[12]+"\n"+kannadamovies[13]+"\n"+kannadamovies[14]+"\n"+kannadamovies[15]+"\n"+kannadamovies[16]+"\n"+kannadamovies[17]+"\n"+kannadamovies[18]+"\n"+kannadamovies[19]+ "\n" +kannadamovies[20]+"\n"+kannadamovies[21]+"\n"+kannadamovies[22]+"\n"+kannadamovies[23]+"\n"+kannadamovies[24]);
System.out.println(" the hindi movies available in netfilx are:"+ "\n" +hindiMovies[0]+"\n"+hindiMovies[1]+"\n"+hindiMovies[2]+"\n"+hindiMovies[3]+"\n"+hindiMovies[4]+"\n"+hindiMovies[5]+"\n"+hindiMovies[6]+"\n"+hindiMovies[7]+"\n"+hindiMovies[8]+"\n"+hindiMovies[9]+ "\n" +hindiMovies[10]+"\n"+hindiMovies[11]+"\n"+hindiMovies[12]+"\n"+hindiMovies[13]+"\n"+hindiMovies[14]+"\n"+hindiMovies[15]+"\n"+hindiMovies[16]+"\n"+hindiMovies[17]+"\n"+hindiMovies[18]+"\n"+hindiMovies[19]+ "\n" +hindiMovies[20]+"\n"+hindiMovies[21]+"\n"+hindiMovies[22]+"\n"+hindiMovies[23]+"\n"+hindiMovies[24]);
System.out.println(" the korean Series available in netfilx are:"+ "\n" +koreanSeries[0]+"\n"+koreanSeries[1]+"\n"+koreanSeries[2]+"\n"+koreanSeries[3]+"\n"+koreanSeries[4]+"\n"+koreanSeries[5]+"\n"+koreanSeries[6]+"\n"+koreanSeries[7]+"\n"+koreanSeries[8]+"\n"+koreanSeries[9]+ "\n" +koreanSeries[10]+"\n"+koreanSeries[11]+"\n"+koreanSeries[12]+"\n"+koreanSeries[13]+"\n"+koreanSeries[14]+"\n"+koreanSeries[15]+"\n"+koreanSeries[16]+"\n"+koreanSeries[17]+"\n"+koreanSeries[18]+"\n"+koreanSeries[19]);

}
}